#!/bin/bash
# kra-thumbnailer, for Gnome 3.10 by Deevad , Nov-2013
# dependencies : unzip and imagemagick
# inspired by Ulhume ODF thumbnailer tutorial on Artisan Numerique


# temp file for the stream
gvfs-cat "$1" > /tmp/kra

# unzip then remove alpha to avoid bad thumb
unzip -p /tmp/kra preview.png | convert -alpha off - "$2"

# cleaning
rm -f /tmp/kra
